openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'https//localhost:8080'
paths:
  /users:
    get:
      description: read all users
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Users'
components:
  schemas:
            UserInfo:
              type: object
              properties:
                username:
                  type: string
                realName:
                  type: string
            Users:
              type: array
              items:
                $ref: '#/components/schemas/UserInfo'

  
