package cz.cvut.tjv.music_store_client.web;

import cz.cvut.tjv.music_store_client.dto.ProductDto;
import cz.cvut.tjv.music_store_client.service.ProductService;
import jakarta.validation.ConstraintViolationException;
import jakarta.validation.Valid;
import jakarta.ws.rs.BadRequestException;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.validation.Validator;
import org.springframework.web.bind.annotation.*;

@Controller
@RequestMapping("/products")
public class ProductController {

    private ProductService productService;

    public ProductController(ProductService productService) {
        this.productService = productService;
    }

    @GetMapping
    public String products(Model model)
    {
        model.addAttribute("allProducts", productService.readAll());
        return "products";
    }


    //===========================
    //EDIT
    //===========================
    @GetMapping("/edit")
    public String editProduct(@RequestParam long id, Model model)
    {
        productService.setActiveProduct(id);
        model.addAttribute("product",productService.readOne().orElseThrow());
        return "productEdit";
    }

    @PostMapping("/edit")
    public String submitEditProduct(@Valid @ModelAttribute ProductDto productDto, BindingResult bindingResult, Model model)
    {

        productService.setActiveProduct(productDto.getId());

        if(bindingResult.hasErrors())
        {
            model.addAttribute("error",true);
            model.addAttribute("errorMsg", bindingResult.getAllErrors().get(0).getDefaultMessage());
            model.addAttribute("product", productService.readOne().orElseThrow());
            return "productEdit";
        }

        try {
            productService.update(productDto);
        }
        catch (BadRequestException e)
        {
            model.addAttribute("error",true);
            model.addAttribute("errorMsg", e.getMessage());
        }
        model.addAttribute("product", productDto);
        return "productEdit";
    }



    //===========================
    //CREATE
    //===========================
    @GetMapping("/create")
    public String createProduct(Model model)
    {

        model.addAttribute("product", new ProductDto());
        return "productCreate";
    }


    @PostMapping("/create")
    public String createProduct(@Valid @ModelAttribute ProductDto productDto, BindingResult bindingResult, Model model)
    {

        if(bindingResult.hasErrors())
        {
            model.addAttribute("error",true);
            model.addAttribute("errorMsg", bindingResult.getAllErrors().get(0).getDefaultMessage());
            model.addAttribute("product", productDto);
            return "productCreate";
        }

        //this one has updated ID by the autogenerated value in backend
        ProductDto tmp = productService.create(productDto);

        return "redirect:/products";
    }

}
