  version: '3.7'

  services:

    postgres:

      image: postgres:latest

      restart: always

      container_name: music_store_db

      environment:

        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=password

      ports:

        - '5432:5432'

      volumes:

        - .docker/postgres-data:/var/lib/postgresql/data


    postgresTest:
      image: postgres:latest

      restart: always

      container_name: music_store_db_testing

      environment:

        - POSTGRES_USER=postgres

        - POSTGRES_PASSWORD=passwordTest


      ports:

        - '5433:5432'

    api:

      image: schrodlm/music_store_server:latest
      container_name: music_store_api
      depends_on:

        - postgres

      ports:

        - '8080:8080'

    client:
      image: schrodlm/music_store_client:latest

      ports:
        - '8081:8081'

