  version: '3.7'


  volumes:
    db-data:

  services:

    postgres:

      image: postgres:latest

      restart: always

      container_name: music_store_db

      environment:
        - POSTGRES_DB=tjv_db
        - POSTGRES_USER=tjv
        - POSTGRES_PASSWORD=tjv

      ports:

        - '5432:5432'

      volumes:

        - db-data:/var/lib/postgresql/data



    api:

      image: schrodlm/music_store_server_final:latest
      container_name: music_store_api
      depends_on:

        - postgres

      ports:

        - '8080:8080'
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://music_store_db/tjv_db
        SPRING_DATASOURCE_USERNAME: tjv
        SPRING_DATASOURCE_PASSWORD: tjv


    client:
      image: schrodlm/music_store_client-final:latest

      ports:
        - '8081:8081'
      environment:
        SERVER_URL: http://api:8080